on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/*"
      - "screenshots/*"
      - "translators.sh"
      - ".github/ISSUE_TEMPLATE/**"
  workflow_dispatch:

permissions: {}

name: CI Build Flatpak
jobs:

  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          # no latest for ARM :(
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.variant.runner }}
    steps:

    - name: Git Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: .flatpak-builder
        key: flatpak-builder-046f9ec-${{ matrix.variant.arch }}-${{ github.run_id }}
        restore-keys: |
          flatpak-builder-046f9ec-${{ matrix.variant.arch }}-
          flatpak-builder-046f9ec-${{ matrix.variant.arch }}

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@401fe28a8384095fc1531b9d320b292f0ee45adb # v6.7
      with:
        bundle: Bazaar.flatpak
        manifest-path: build-aux/flatpak/io.github.kolunmi.Bazaar.json
        # caching is broken upstream
        # https://github.com/flatpak/flatpak-github-actions/issues/239
        # this is only true because we need to call fb with --ccache, this will upload useless cache
        cache: true
        restore-cache: false
        arch: ${{ matrix.variant.arch }}
        verbose: true

    - name: Write new cache
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: .flatpak-builder
        key: flatpak-builder-046f9ec-${{ matrix.variant.arch }}-${{ github.run_id }}
